### ISSUE TITLE
Add player info in state printing

### ISSUE THREAD

**Issue by Thomatous** [ThomasPapathimiopoulos/Wave-Function-Collapse#1]
Include info for each team in each state print such as:
- Number of players
- Number of times evolved
- Highest attack
- Highest health
- Highest movement

**Comment by ThomasPapathimiopoulos** [comment]
https://github.com/savioxavier/pyboxen might be useful

**Comment by Thomatous** [comment]
https://github.com/Textualize/rich/

**Comment by Thomatous** [comment]
Highest stats not added in current implementation.
